baseURL = "https://roster.bangunan.co/"
languageCode = "id"
title = "Bata Roster Minimalis | Jual Bata Roster Minimalis Berbagai Model"
theme = "saeseen-hugo"
summaryLength = 25
paginate = 6

[permalinks]
  post = "/:slug/"
  page = "/:slug/"
  category = "/:slug/"

[params]
  # Site-wide settings
  meta_description = "Jual Bata Roster Minimalis - Bata Roster dengan berbagai model untuk desain ventilasi, pagar dan dekorasi bangunan Anda"
  viewport = "width=device-width, initial-scale=1.0"
  fontawesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
  logo = "/images/logo/bangunanco-logo-web.png"
  logo_amp = "/images/logo/bangunanco-512x512.png"
  footer_logo = "/images/logo/bangunanco-logo-putih.png"
  favicon = "/images/logo/bangunanco-512x512.png"
  featured_image = "/images/admin/featured-image.png"
  author = "K. Yaman"
  telepon = "//+6285776786091"
  whatsapp = "//api.whatsapp.com/send?phone=6285776786091&text=*Halo bangunan.co*%20%3A"
  enableWhatApps = true
  enableTelepon = true
  tocMinWordCount = 300
  tableOfContent = "Daftar Isi:"
  geo_latitude = -6.595038
  geo_longitude = 106.817787
  opening_hours = "Mo-Sa 08:00-17:00"

  # Schema settings
  keywords = ["jual bata roster", "bata roster minimalis", "bata roster berbagai model", "bata roster ventilasi", "bata roster dekorasi", "bata roster harga terjangkau"]
  base_price = 15000
  price_range = 5000
  free_shipping = false
  materials = [
  "Bata Roster Ventilasi",
  "Bata Roster Pagar",
  "Bata Roster Dekorasi Dinding",
  "Bata Roster Custom Desain",
  "Bata Roster Berbagai Model"
  ]
  categories = ["Bata Roster", "Material Bangunan", "Dekorasi Dinding"]
  payment_methods = ["COD (Cash On Delivery)", "Transfer Bank", "Bayar Ditempat", "Transfer Setelah Terkirim"]
  area_served = ["Jakarta", "Bogor", "Depok", "Tangerang", "Bekasi", "Cikarang", "Karawang", "Subang", "Cikampek", "Purwakarta", "Rangkas Bitung", "Serang"]
  return_policies = [
  "Barang bisa ditukar dalam 1 hari jika tidak sesuai.",
  "Barang dapat ditolak jika bata roster tidak sesuai spesifikasi.",
  "Pengembalian gratis untuk produk yang tidak sesuai pesanan."
  ]

 # Hero Section
  hero_image = "/images/admin/bg_bangunanco.png"
  hero_title = "Bata Roster Minimalis Berkualitas"
  hero_description = "Kami menawarkan berbagai model bata roster minimalis berkualitas tinggi yang cocok untuk ventilasi dan dekorasi bangunan Anda. Solusi ideal untuk menciptakan sirkulasi udara yang baik serta estetika yang menarik dengan bahan yang kuat dan tahan lama."
  hero_cta_text = "Pelajari Lebih Lanjut"
  services_cta_text = "Cek Katalog Roster"

  # Footer Section
  footer_about_title = "Mengapa Memilih Kami"
  footer_about_description = "Kami menyediakan berbagai model bata roster minimalis berkualitas tinggi dengan harga kompetitif. Layanan pengiriman cepat dan konsultasi gratis untuk membantu Anda memilih roster yang sesuai dengan kebutuhan bangunan Anda."
  footer_services_title = "Kenapa Pilih Kami"
  footer_contact_title = "Kontak Kami"
  footer_bottom_text = "@2024 Bangunan.co. Semua Hak Dilindungi."

  # Testimonials Section
  testimonials_title = "Apa Kata Klien Kami"

  [[params.footer_services]]
  text = "roster.bangunan.co menawarkan berbagai model bata roster berkualitas tinggi dengan harga bersaing. Kami mengutamakan kepuasan pelanggan dengan produk roster yang kuat, estetis, dan fungsional. Pilih kami untuk kebutuhan bata roster Anda dengan kualitas terbaik."

  [[params.footer_contact]]
    icon = "fas fa-map-marker-alt"
    text = "Jalan Lkr. Dramaga No. 09, Bogor - JaBar"
  [[params.footer_contact]]
    icon = "fas fa-phone-alt"
    text = "+62 857-7678-6091"
  [[params.footer_contact]]
    icon = "fas fa-envelope"
    text = "bangunanco@gmail.com"

[[params.testimonials]]
  avatar = "/images/admin/avatar1.png"
  name = "{Budi|Joko|Andi|Eko|Rudi|Fajar|Hendra|Samsul|Agus|Dedi}"
  message = "{Saya menggunakan bata roster dari roster.bangunan.co untuk {ventilasi|sirkulasi udara} rumah saya. Kualitasnya {sangat baik|luar biasa|kokoh} dan desainnya {menarik|modern|elegan}.|Bata roster dari roster.bangunan.co sangat {berkualitas|kokoh} dan desainnya {menarik|unik}, cocok untuk ventilasi rumah saya.}"
  response = "{Terima kasih atas kepercayaan Anda! Kami senang dapat menyediakan produk bata roster berkualitas untuk proyek Anda.|Kami sangat menghargai kepercayaan Anda. Terima kasih telah memilih produk kami!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar2.png"
  name = "{Siti|Rina|Dewi|Wati|Lia|Nina|Ratna|Indah|Sari|Ayu}"
  message = "{roster.bangunan.co sangat {membantu|bermanfaat} dalam {memilih|menyediakan} bata roster untuk {dekorasi pagar|ornamen} rumah saya. Produk yang saya beli {sangat cocok|pas} dan berkualitas {tinggi|premium}.|Pelayanan roster.bangunan.co sangat {baik|memuaskan} dan bata roster yang saya pilih {sangat berkualitas|benar-benar sesuai dengan harapan}.}"
  response = "{Kami sangat menghargai ulasan Anda. Senang mendengar bahwa Anda puas dengan bata roster dari kami.|Terima kasih, atas kepercayaannya. Kami senang dapat menyediakan produk berkualitas untuk Anda!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar3.png"
  name = "{Joko|Budi|Andi|Eko|Rudi|Fajar|Hendra|Samsul|Agus|Dedi}"
  message = "{Bata roster dari roster.bangunan.co sangat {kokoh|kuat} dan cocok untuk proyek {gedung|konstruksi} saya. Proses pengirimannya juga {cepat|tepat waktu|efisien}.|Saya menggunakan bata roster dari roster.bangunan.co untuk proyek gedung dan sangat puas dengan {ketahanannya|kualitasnya}. Pengirimannya sangat cepat dan tepat waktu.}"
  response = "{Terima kasih! Kami berkomitmen untuk menyediakan produk bata roster berkualitas dengan layanan terbaik.|Kami sangat menghargai kepercayaan Anda. Terima kasih telah memilih kami!}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar4.png"
  name = "{Andi|Budi|Joko|Eko|Rudi|Fajar|Hendra|Samsul|Agus|Dedi}"
  message = "{Saya sangat puas dengan bata roster dari roster.bangunan.co. Kualitasnya {sangat baik|luar biasa|kokoh} dan {sangat sesuai|tepat} untuk proyek saya.|Bata roster dari roster.bangunan.co {benar-benar sesuai|sangat cocok} untuk proyek saya. Kualitasnya sangat {bagus|terbaik} dan tahan lama.}"
  response = "{Senang mendengar Anda puas dengan bata roster kami. Terima kasih atas kepercayaannya!|Terima kasih, atas kepercayaannya. Kami senang dapat memberikan produk terbaik untuk proyek Anda.}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar5.png"
  name = "{Rina|Siti|Dewi|Wati|Lia|Nina|Ratna|Indah|Sari|Ayu}"
  message = "{Pelayanan roster.bangunan.co sangat {memuaskan|baik}. Produk bata roster yang saya beli sangat {berkualitas|kokoh} dan sesuai dengan harapan saya.|Saya sangat puas dengan bata roster dari roster.bangunan.co. {Kualitasnya|Barangnya} sangat {baik|berkualitas} dan sesuai dengan desain yang saya inginkan.}"
  response = "{Terima kasih! Kami senang dapat membantu mewujudkan proyek Anda dengan bata roster terbaik.|Kami sangat menghargai kepercayaan Anda. Terima kasih sudah memilih kami!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar6.png"
  name = "{Eko|Budi|Joko|Andi|Rudi|Fajar|Hendra|Samsul|Agus|Dedi}"
  message = "{Bata roster dari roster.bangunan.co sangat {sesuai|cocok} dengan kebutuhan {dekorasi dinding|ornamen} rumah saya. Pengirimannya {cepat|tepat waktu|aman} dan hasilnya {memuaskan|sesuai harapan}.|Saya memilih bata roster dari roster.bangunan.co untuk dekorasi dinding dan sangat puas dengan {pengirimannya|produknya}. Produk tiba tepat waktu dan berkualitas.}"
  response = "{Kami senang mendengar bahwa Anda puas dengan produk bata roster kami. Terima kasih atas ulasannya!|Terima kasih, atas ulasan positifnya. Kami selalu berkomitmen untuk memberikan produk terbaik.}"
  rating = 5

[[params.tabelItems]]
  name = "Bata Roster Ventilasi"
  price = "15.000 /pcs"
[[params.tabelItems]]
  name = "Bata Roster Pagar"
  price = "18.000 /pcs"
[[params.tabelItems]]
  name = "Bata Roster Dekorasi"
  price = "20.000 /pcs"
[[params.tabelItems]]
  name = "Bata Roster Custom"
  price = "25.000 /pcs"
[[params.tabelItems]]
  name = "Bata Roster warna-warni"
  price = "22.000 /pcs"

[params.appliList]
  "Bata Roster Ventilasi" = "dinding ventilasi, ruang tamu, ruang keluarga"
  "Bata Roster Pagar" = "pagar rumah, pagar taman"
  "Bata Roster Dekorasi" = "dinding interior, dinding eksterior"
  "Bata Roster Custom" = "desain khusus untuk proyek besar"
  "Bata Roster Berbagai Model" = "dinding ventilasi, pagar, dekorasi bangunan"

[params.kegunaanList]
  "Bata Roster Ventilasi" = "memperbaiki sirkulasi udara di ruangan"
  "Bata Roster Pagar" = "menambah estetika pada pagar rumah"
  "Bata Roster Dekorasi" = "meningkatkan tampilan dekoratif dinding"
  "Bata Roster Custom" = "solusi desain unik untuk proyek bangunan"
  "Bata Roster Berbagai Model" = "pilihan model untuk berbagai keperluan arsitektur"

  # Menu Section
  [[params.menu_items]]
    title = "Beranda"
    url = "/"
  [[params.menu_items]]
    title = "Profile"
    url = "https://bangunan.co/profile/"
  [[params.menu_items]]
    title = "Daftar Harga"
    url = "https://bangunan.co/daftar-harga/"

[params.header]
   title = "Jual Bata Roster Minimalis | "
   highlight = "Bangunan.co"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 100

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "AMP"]

[outputFormats]
  [outputFormats.AMP]
    mediaType = "text/html"
    baseName = "amp/index"
    path = ""
    isPlainText = false
    permalinkable = true
    rel = "amphtml"